### ISSUE TITLE
"TypeError: expected string or buffer" exception while installi mopidy-tunein

### ISSUE THREAD

**Issue by jezalb** [kingosticks/mopidy-tunein#12]
Hi,

I got an exception trying to install mopidy-tunein on Raspbmc. Here is stackstrace:

Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 347, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 497, in install
    and req.installed_version in distribute_req):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources.py", line 2851, in __contains__
    return self.specifier.contains(item, prereleases=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/specifiers.py", line 651, in contains
    item = parse(item)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/version.py", line 41, in parse
    return Version(version)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/version.py", line 202, in __init__
    match = self._regex.search(version)
TypeError: expected string or buffer

I use this command to install (tried sudo and no-sudo version): 
pip install Mopidy-TuneIn

Is it possible that I miss some dependencies?

**Comment by kingosticks** [comment]
If this is till a problem could you please paste the entire install log (please use dpaste or similar). Is this limited to just tunein or are you unable to install any mopidy extensions from pip?

**Comment by kingosticks** [comment]
OK, looks like https://github.com/pypa/pip/issues/2272
