### ISSUE TITLE
Mopidy crashes

### ISSUE THREAD

**Issue by Mebus** [kingosticks/mopidy-tunein#20]
After installing this, my mopidy crashes:

<code>
2015-06-28 12:26:17,289 ERROR [10848:MainThread] mopidy.commands: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 274, in run
    backends = self.start_backends(config, backend_classes, audio)
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 352, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/actor.py", line 48, in __init__
    proxy=proxy)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/api.py", line 57, in __init__
    if len(proxy):
TypeError: object of type 'NoneType' has no len()
2015-06-28 12:26:17,300 INFO [10848:MainThread] mopidy.commands: Stopping Mopidy frontends
2015-06-28 12:26:17,305 INFO [10848:MainThread] mopidy.commands: Stopping Mopidy core
2015-06-28 12:26:17,308 INFO [10848:MainThread] mopidy.commands: Stopping Mopidy backends
</code>

Mebus

**Comment by jodal** [comment]
It looks like this is the fault of Mopidy-radio-de, not Mopidy-TuneIn.
